### ISSUE TITLE
ES modules is not supported

### ISSUE THREAD

**Issue by pubkey** [sindresorhus/convert-hrtime#4]
When upgrading to version `5.0.0` I get a strange error when importing the module.

I import the module into typescript like shown in the readme.
```typescript
import convertHrtime from 'convert-hrtime';
```

When I start the node process, I get the following error:

```bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/dnl/workspace/rxdb/node_modules/convert-hrtime/index.js
require() of ES modules is not supported.
require() of /home/dnl/workspace/rxdb/node_modules/convert-hrtime/index.js from /home/dnl/workspace/rxdb/test_tmp/performance.test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/dnl/workspace/rxdb/node_modules/convert-hrtime/package.json.

    at new NodeError (node:internal/errors:329:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1109:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/dnl/workspace/rxdb/test_tmp/performance.test.js:15:45)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:177:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/dnl/workspace/rxdb/node_modules/mocha/lib/esm-utils.js:7:14)
    at async Object.exports.loadFilesAsync (/home/dnl/workspace/rxdb/node_modules/mocha/lib/esm-utils.js:55:20)
    at async singleRun (/home/dnl/workspace/rxdb/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/dnl/workspace/rxdb/node_modules/mocha/lib/cli/run.js:362:5)

```

This problem did not occur in the previous version.

**Comment by sindresorhus** [comment]
Please read the release notes. It has a link that explains everything: https://github.com/sindresorhus/convert-hrtime/releases/tag/v4.0.0
