### ISSUE TITLE
Does not work out of the box for a node typescript project

### ISSUE THREAD

**Issue by vongohren** [sindresorhus/convert-hrtime#5]
I installed this recently and expected it to work out of the box.
But got this error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/person/sdks/repo/node_modules/convert-hrtime/index.js
require() of ES modules is not supported.
require() of /Users/person/sdks/repo/node_modules/convert-hrtime/index.js from /Users/person/sdks/repo/src/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/person/sdks/repo/node_modules/convert-hrtime/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/person/sdks/repo/src/index.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/Users/person/sdks/repo/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/person/sdks/repo/node_modules/ts-node/src/index.ts:1059:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My setup is: 
Node: 12.22
Typescript: 4.2.4
Ts-node: 9.1.1

**Comment by vongohren** [comment]
Duplicate of: https://github.com/sindresorhus/convert-hrtime/issues/4
